# Generated by Django 5.1 on 2024-09-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panaderia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='domicilio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
