# Generated by Django 5.1 on 2024-09-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panaderia', '0002_alter_cliente_domicilio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='domicilio',
            field=models.CharField(max_length=200),
        ),
    ]
