# Generated by Django 5.1 on 2024-09-21 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panaderia', '0003_alter_cliente_domicilio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='servicio',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
