# Generated by Django 5.1 on 2024-09-24 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panaderia', '0005_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
    ]
