# Generated by Django 5.1 on 2024-09-24 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panaderia', '0005_producto'),
        ('pedido', '0002_alter_pedido_cliente_alter_pedido_servicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panaderia.producto'),
        ),
    ]
