# Generated by Django 5.1 on 2024-09-24 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panaderia', '0006_remove_producto_categoria'),
        ('pedido', '0003_alter_pedido_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panaderia.panaderia'),
        ),
    ]
